# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='C_T',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True, verbose_name=b'\xe9\xa2\x98\xe7\x9b\xae')),
                ('optiona', models.CharField(max_length=20, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9a')),
                ('optionb', models.CharField(max_length=20, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9b')),
                ('optionc', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9c')),
                ('optiond', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9d')),
                ('correctanswer', models.CharField(max_length=1, verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe9\x80\x89\xe9\xa1\xb9')),
                ('correctrate', models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe7\x8e\x87')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name=b'\xe9\x9a\xbe\xe6\x98\x93\xe7\xb3\xbb\xe6\x95\xb0')),
                ('analysis', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90')),
                ('knowledgepoint', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe7\x9f\xa5\xe8\xaf\x86\xe7\x82\xb9')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u9009\u62e9\u9898',
                'verbose_name_plural': '\u9009\u62e9\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scname', models.CharField(max_length=20, unique=True, verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7\xe5\x90\x8d\xe7\xa7\xb0')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='ClsPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_id', models.CharField(max_length=50, null=True, verbose_name=b'\xe9\x80\x89\xe6\x8b\xa9\xe9\xa2\x98\xe9\x9b\x86')),
                ('fill_id', models.CharField(max_length=50, null=True, verbose_name=b'\xe5\xa1\xab\xe7\xa9\xba\xe9\xa2\x98\xe9\x9b\x86\xe5\x90\x88')),
                ('judgment_id', models.CharField(max_length=50, null=True, verbose_name=b'\xe5\x88\xa4\xe6\x96\xad\xe9\xa2\x98\xe9\x9b\x86\xe5\x90\x88')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('chapter', models.CharField(max_length=20, verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82')),
            ],
            options={
                'verbose_name': '\u8bfe\u5802\u7ec3\u4e60',
                'verbose_name_plural': '\u8bfe\u5802\u7ec3\u4e60\u8868',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, unique=True, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe5\x90\x8d\xe7\xa7\xb0')),
                ('description', models.CharField(default=b'\xe6\x9a\x82\xe6\x97\xb6\xe6\xb2\xa1\xe6\x9c\x89\xe6\x8f\x8f\xe8\xbf\xb0', max_length=50, verbose_name=b'\xe8\xaf\xbe\xe7\xa8\x8b\xe6\x8f\x8f\xe8\xbf\xb0')),
            ],
            options={
                'verbose_name': '\u8bfe\u7a0b',
                'verbose_name_plural': '\u8bfe\u7a0b\u8868',
            },
        ),
        migrations.CreateModel(
            name='Fill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True, verbose_name=b'\xe9\xa2\x98\xe7\x9b\xae')),
                ('correctanswer', models.CharField(max_length=20, verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe7\xad\x94\xe6\xa1\x88')),
                ('correctrate', models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe7\x8e\x87')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name=b'\xe9\x9a\xbe\xe6\x98\x93\xe7\xb3\xbb\xe6\x95\xb0')),
                ('analysis', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90')),
                ('knowledgepoint', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe7\x9f\xa5\xe8\xaf\x86\xe7\x82\xb9')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u586b\u7a7a\u9898',
                'verbose_name_plural': '\u586b\u7a7a\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True, verbose_name=b'\xe9\xa2\x98\xe7\x9b\xae')),
                ('correctanswer', models.BooleanField(verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe7\xad\x94\xe6\xa1\x88')),
                ('correctrate', models.IntegerField(blank=True, null=True, verbose_name=b'\xe6\xad\xa3\xe7\xa1\xae\xe7\x8e\x87')),
                ('difficulty', models.IntegerField(blank=True, null=True, verbose_name=b'\xe9\x9a\xbe\xe6\x98\x93\xe7\xb3\xbb\xe6\x95\xb0')),
                ('analysis', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'\xe8\xa7\xa3\xe6\x9e\x90')),
                ('knowledgepoint', models.CharField(blank=True, max_length=30, null=True, verbose_name=b'\xe7\x9f\xa5\xe8\xaf\x86\xe7\x82\xb9')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('course', models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe8\xaf\xbe\xe7\xa8\x8b')),
            ],
            options={
                'verbose_name': '\u5224\u65ad\u9898',
                'verbose_name_plural': '\u5224\u65ad\u9898\u8868',
            },
        ),
        migrations.CreateModel(
            name='PracticeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costtime', models.IntegerField(verbose_name=b'\xe7\xbb\x83\xe4\xb9\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('hesitateinfo', models.CharField(max_length=100, verbose_name=b'\xe7\x8a\xb9\xe8\xb1\xab\xe4\xbf\xa1\xe6\x81\xaf')),
                ('errorinfo', models.CharField(max_length=100, verbose_name=b'\xe9\x94\x99\xe8\xaf\xaf\xe4\xbf\xa1\xe6\x81\xaf')),
                ('position', models.CharField(max_length=10, verbose_name=b'\xe7\xad\x94\xe9\xa2\x98\xe4\xba\xba\xe7\xbb\x8f\xe7\xba\xac\xe5\xba\xa6')),
                ('clspratice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpis.ClsPractice', verbose_name=b'\xe8\xaf\xbe\xe5\xa0\x82\xe7\xbb\x83\xe4\xb9\xa0')),
            ],
            options={
                'verbose_name': '\u7b54\u9898\u8bb0\u5f55',
                'verbose_name_plural': '\u7b54\u9898\u8bb0\u5f55\u8868',
            },
        ),
        migrations.CreateModel(
            name='PubPractice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forclass', models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x92\x88\xe5\xaf\xb9\xe7\x8f\xad\xe7\xba\xa7')),
                ('publish_date', models.DateTimeField(verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe6\x97\xa5\xe6\x9c\x9f')),
                ('practice_time', models.IntegerField(verbose_name=b'\xe7\xbb\x83\xe4\xb9\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('sata', models.SmallIntegerField(verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('publish_loc', models.CharField(max_length=10, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe5\x9c\xb0\xe7\x82\xb9\xe7\xbb\x8f\xe7\xba\xac\xe5\xba\xa6')),
                ('clspractice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.ClsPractice', verbose_name=b'\xe8\xaf\xbe\xe5\xa0\x82\xe7\xbb\x83\xe4\xb9\xa0')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u7ec3\u4e60',
                'verbose_name_plural': '\u53d1\u5e03\u7ec3\u4e60\u8868',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssex', models.CharField(choices=[(b'\xe7\x94\xb7', b'\xe7\x94\xb7'), (b'\xe5\xa5\xb3', b'\xe5\xa5\xb3')], max_length=2, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab')),
                ('clz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpis.Clazz', verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x9f\xba\xe6\x9c\xac\xe4\xbf\xa1\xe6\x81\xaf')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.ManyToManyField(through='cpis.C_T', to='cpis.Clazz')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xe5\x9f\xba\xe6\x9c\xac\xe4\xbf\xa1\xe6\x81\xaf')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08\u8868',
            },
        ),
        migrations.AddField(
            model_name='pubpractice',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Teacher', verbose_name=b'\xe6\x95\x99\xe5\xb8\x88'),
        ),
        migrations.AddField(
            model_name='practicerecord',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Student', verbose_name=b'\xe5\xad\xa6\xe7\x94\x9f\xe7\xbc\x96\xe5\x8f\xb7'),
        ),
        migrations.AddField(
            model_name='clspractice',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Course', verbose_name=b'\xe6\x89\x80\xe5\xb1\x9e\xe8\xaf\xbe\xe7\xa8\x8b'),
        ),
        migrations.AddField(
            model_name='clspractice',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Teacher', verbose_name=b'\xe6\x95\x99\xe5\xb8\x88'),
        ),
        migrations.AddField(
            model_name='c_t',
            name='clzz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Clazz', verbose_name=b'\xe7\x8f\xad\xe7\xba\xa7'),
        ),
        migrations.AddField(
            model_name='c_t',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cpis.Course', verbose_name=b'\xe6\x89\x80\xe5\xb8\xa6\xe8\xaf\xbe\xe7\xa8\x8b'),
        ),
        migrations.AddField(
            model_name='c_t',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpis.Teacher', verbose_name=b'\xe6\x95\x99\xe5\xb8\x88'),
        ),
    ]
