# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ssex',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name=b'\xe6\x80\xa7\xe5\x88\xab'),
        ),
    ]
