# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0003_clazz_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='optione',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9e'),
        ),
    ]
