# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-28 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0004_choice_optione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clspractice',
            name='chapter',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=b'\xe7\xab\xa0\xe8\x8a\x82'),
        ),
    ]
