# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-12-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0006_auto_20161230_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicerecord',
            name='position',
            field=models.CharField(max_length=100, verbose_name=b'\xe7\xad\x94\xe9\xa2\x98\xe4\xba\xba\xe7\xbb\x8f\xe7\xba\xac\xe5\xba\xa6'),
        ),
        migrations.AlterField(
            model_name='pubpractice',
            name='publish_loc',
            field=models.CharField(max_length=100, verbose_name=b'\xe5\x8f\x91\xe5\xb8\x83\xe5\x9c\xb0\xe7\x82\xb9\xe7\xbb\x8f\xe7\xba\xac\xe5\xba\xa6'),
        ),
    ]
