# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0007_auto_20161230_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='optiona',
            field=models.CharField(max_length=50, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9a'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='optionb',
            field=models.CharField(max_length=50, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9b'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='optionc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9c'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='optiond',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9d'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='optione',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'\xe9\x80\x89\xe9\xa1\xb9e'),
        ),
    ]
