# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpis', '0008_auto_20170101_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicerecord',
            name='errorinfo',
            field=models.CharField(max_length=5128, verbose_name=b'\xe9\x94\x99\xe8\xaf\xaf\xe4\xbf\xa1\xe6\x81\xaf'),
        ),
    ]
